Added Calibration and Logging Code
Virtana/accurate-aprilgroup-tracking pull request #6
Opened 2021-06-14 16:08 UTC by zoes-full-stack

2021-06-14 20:44 UTC, RajivJGM requested changes
Nice work! The logger will definitely come in handy. Left a few comments (mostly nits).

2021-06-14 20:44 UTC, RajivJGM commented on aprilgroup_tracking/main.py
> +    if calibrate.try_load_intrinsic():
Nit: to avoid code duplication, you can use:
```
if not calibrate.try_load_intrinsic():
    calibrate.start_intrinsic_calibration() 
    calibrate.calculate_intrinsic()
    calibrate.load_intrinsic()
mtx, dist, rvecs, tvecs = calibrate.mtx, calibrate.dist, calibrate.rvecs, calibrate.tvecs
print(mtx)
```

2021-06-14 20:44 UTC, RajivJGM commented on aprilgroup_tracking/main.py
> +        calibrate.start_intrinsic_calibration()
Will calling start_intrinsics_calibration() without following up with calculate_intrinsics() immediately after ever be performed? If not, I suggest calling start_intrinsics_calibration()  at the beginning of calculate_intrinsics().
Also, perhaps start_intrinsics_calibration() should return objp as it's not used beyond calculate_intrinsics() (so no need for it to be an instance variable)

2021-06-14 20:44 UTC, RajivJGM commented on aprilgroup_tracking/calibration/calibrate_camera.py
> +    def __init__(self, logger):
Nit: Let's follow this style guide for naming conventions: https://google.github.io/styleguide/pyguide.html#3164-guidelines-derived-from-guidos-recommendations.
It's particularly useful in telling at a glance what's internal and public facing within a class.

2021-06-14 20:44 UTC, RajivJGM commented on aprilgroup_tracking/calibration/calibrate_camera.py
> +    def start_intrinsic_calibration(self):
Nit: type hinting is encouraged. Use `() -> None` if nothing is returned.

2021-06-15 13:50 UTC, zoes-full-stack commented on aprilgroup_tracking/main.py
> +    if calibrate.try_load_intrinsic():
Thank you! This is much better!

2021-06-15 16:12 UTC, zoes-full-stack commented
I added mypy linting and the typing for variables! I hope I did it right!

2021-06-15 19:07 UTC, RajivJGM reviewed
One final comment, otherwise looks good!

2021-06-15 19:07 UTC, RajivJGM commented on aprilgroup_tracking/calibration/calibrate_camera.py
>      def start_intrinsic_calibration(self):
This should now return () -> np.ndarray

2021-06-15 20:32 UTC, merged